# Name of your site (displayed in the header)
name: Fatma-Tal lab

# Short bio or description (displayed in the header)
description: Chemical Engineering Lab Notebook

# URL of your avatar or profile pic
avatar: ""

# Includes an icon in the footer for each username you enter
footer-links:
  github: fatmayassin2001-star
  email: fatmayassin2001@gmail.com

# Your website URL
url: "https://fatmayassin2001-star.github.io"

# Repository name
baseurl: "/Fatma-lab-notebook"

permalink: /:title/

# Jekyll configurations
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# תיקון נתיב ה-Sass כדי למנוע את קריסת השרת
sass:
  sass_dir: _sass
  style: expanded

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
