#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Fatma-Tal lab

# Short bio or description (displayed in the header)
description: Chemical Engineering Lab Notebook

# URL of your avatar or profile pic
avatar: ""

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: fatmayassin2001-star
  instagram:
  linkedin:
  pinterest:
  rss:
  twitter:
  stackoverflow:
  youtube:
  googleplus:

# Enter your Disqus shortname
disqus:

# Enter your Google Analytics tracking code
google_analytics:

# Your website URL
url: "https://fatmayassin2001-star.github.io"

# Repository name
baseurl: "/Fatma-lab-notebook"

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Set the Sass partials directory
sass:
  style: :expanded

# Use the following plug-ins
gems:
  - jekyll-sitemap
  - jekyll-feed

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
